[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# General
anyhow = "1.0"

# Logging
env_logger = "0.9"
log = "0.4"

# Tokio
tokio = { version = "1", features = ["full"] }

# Shutdown
tokio-graceful-shutdown = "0.2"
async-trait = "0.1"

# Command line arguments
# TODO replace with proper 3.0 version once released
clap = "3.0.0-beta.5"
